name: "Deploy Package Documentation to Pages"

on:
  push:
    branches: [main] # branch to trigger deployment

  workflow_dispatch:

jobs:
  pages:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - id: deployment
      uses: sphinx-notes/pages@e9c8f79f285fb41a150ba6e08a3c2a29635e7ee1  # v3.5
      with:
        publish: false
        documentation_path: ./docs
        pyproject_extras: docs
    - uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e  # v4.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ steps.deployment.outputs.artifact }} 
        publish_branch: gh-pages  # default: gh-pages
        commit_message: ${{ github.event.head_commit.message }}

